<?php
// +----------------------------------------------------------------------
// | EnumException.php [ WE CAN DO IT JUST THINK IT ]
// +----------------------------------------------------------------------
// | Copyright (c) 2016-2017 xiaolin All rights reserved.
// +----------------------------------------------------------------------
// | Author: xiaolin <462441355@qq.com> <https://github.com/missxiaolin>
// +----------------------------------------------------------------------
namespace Tests;
use Lin\Swoole\Common\File\File;
use Lin\Swoole\Common\Redis\Redis;
use PHPUnit\Framework\TestCase as UnitTestCase;

abstract class TestCase extends UnitTestCase
{
    public $redis;

    public $file = TESTS_PATH . '/test.cache';

    /**
     * TestCase constructor.
     * @param null $name
     * @param array $data
     * @param string $dataName
     */
    public function __construct($name = null, array $data = [], $dataName = '')
    {
        $config = include TESTS_PATH . '/_ci/config.php';

        $host = $config['redisHost'];
        $auth = $config['redisAuth'];
        $db = $config['redisDb'];
        $port = $config['redisPort'];

        $this->redis = Redis::getInstance($host, $auth, $db, $port);

        parent::__construct($name, $data, $dataName);
    }

    protected function setUp()
    {
        File::getInstance()->put($this->file, 'init');
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}